#!/usr/bin/env python3
"""Measure the advance of every glyph the Minecraft default font draws.

The advance is what a text layout needs: the pixels one glyph moves the pen, the one pixel gap
between glyphs included. The client computes it from the font atlas, so the only honest source is
the client itself.

    python3 measure-glyph-widths.py 26.2 > glyph-widths.txt

The script downloads the client jar of the given version from Mojang, reads the font definition and
the atlas images, and prints one line per glyph that does not advance the default six pixels. The
jar is deleted at the end. No downloaded file enters a repository.

The arithmetic is the client's own, read from BitmapProvider in the 26.2 client:

    cellWidth  = imageWidth / columns
    cellHeight = imageHeight / rows
    scale      = height / cellHeight        (height defaults to 8)
    advance    = (int) (0.5 + inkWidth * scale) + 1

where inkWidth is the column of the rightmost pixel that is not transparent, counted from the left
edge of the cell. An empty cell advances one pixel.

Requires Pillow.
"""

import json
import pathlib
import sys
import tempfile
import urllib.request
import zipfile

from PIL import Image

MANIFEST = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
DEFAULT_ADVANCE = 6


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read()


def client_jar(version, into):
    manifest = json.loads(fetch(MANIFEST))
    entry = next((v for v in manifest["versions"] if v["id"] == version), None)
    if entry is None:
        raise SystemExit(f"version {version} is not in the manifest")
    meta = json.loads(fetch(entry["url"]))
    jar = into / "client.jar"
    jar.write_bytes(fetch(meta["downloads"]["client"]["url"]))
    return jar


def advances(assets):
    """Codepoint to advance, for every provider of the default font. The first provider wins."""
    table = {}

    def put(codepoint, advance):
        table.setdefault(codepoint, advance)

    space = json.loads((assets / "minecraft/font/include/space.json").read_text())
    for provider in space["providers"]:
        if provider["type"] == "space":
            for glyph, advance in provider["advances"].items():
                put(ord(glyph), int(advance))

    default = json.loads((assets / "minecraft/font/include/default.json").read_text())
    for provider in default["providers"]:
        if provider["type"] != "bitmap":
            continue
        texture = assets / "minecraft/textures" / provider["file"].split(":", 1)[1]
        image = Image.open(texture).convert("RGBA")
        pixels = image.load()
        rows = provider["chars"]
        columns = len(rows[0])
        cell_width = image.width // columns
        cell_height = image.height // len(rows)
        scale = provider.get("height", 8) / cell_height
        for row, line in enumerate(rows):
            for column, glyph in enumerate(line):
                if ord(glyph) == 0:
                    continue
                ink = 0
                for x in range(cell_width - 1, -1, -1):
                    if any(pixels[column * cell_width + x, row * cell_height + y][3]
                           for y in range(cell_height)):
                        ink = x + 1
                        break
                put(ord(glyph), int(0.5 + ink * scale) + 1)
    return table


def main():
    version = sys.argv[1] if len(sys.argv) > 1 else "26.2"
    with tempfile.TemporaryDirectory() as work:
        work = pathlib.Path(work)
        with zipfile.ZipFile(client_jar(version, work)) as jar:
            for name in jar.namelist():
                if name.startswith("assets/minecraft/font/") or name.startswith("assets/minecraft/textures/font/"):
                    jar.extract(name, work)
        table = advances(work / "assets")

    print(f"# Minecraft {version} default font. One line per glyph that does not advance"
          f" {DEFAULT_ADVANCE} pixels.")
    print("# codepoint (hex) and advance (pixels, the trailing gap included).")
    print("# Generated by measure-glyph-widths.py from the official client jar. Do not edit by hand.")
    for codepoint, advance in sorted(table.items()):
        if advance != DEFAULT_ADVANCE:
            print(f"{codepoint:04X} {advance}")


if __name__ == "__main__":
    main()
