package com.uxplima.uxmlib.text;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Minecraft default-font advance widths, in pixels, including the one-pixel gap between glyphs. Used by
 * {@link CenteredTextPadder} to work out the leading spaces that centre a line, and by anything else that has
 * to know how wide a string will draw.
 *
 * <p>The numbers are measured from the client's own font atlases rather than guessed: {@code advance =
 * (int) (0.5 + inkWidth * scale) + 1}, which is the arithmetic the client itself uses. They live in the
 * resource {@code uxmlib/glyph-widths.txt}, one line per glyph that is not the {@value #DEFAULT_WIDTH}-pixel
 * default, regenerated by {@code tools/glyph-widths/measure-glyph-widths.py} when a Minecraft version changes
 * the font.
 *
 * <p>A code point the file does not name advances {@value #DEFAULT_WIDTH} pixels. That is right for most of
 * the font and wrong for the glyphs a fallback provider draws, so centring stays what it has always been:
 * cosmetic arithmetic that is close rather than exact.
 *
 * <p>Measure by code point. {@link #widthOf(char, boolean)} cannot see an emoji: its two surrogates are not
 * glyphs and each would be counted as a default-width one. {@link #widthOf(CharSequence, boolean)} walks a
 * string by code point and is what a caller should reach for.
 */
public final class GlyphWidthTable {

    private GlyphWidthTable() {}

    /** Default advance for any glyph the table does not name. */
    public static final int DEFAULT_WIDTH = 6;

    /** Advance for the space character. */
    public static final int SPACE_WIDTH = 4;

    /** Extra pixels a bold glyph adds. */
    public static final int BOLD_EXTRA = 1;

    /** The measured table, as {@code codepoint -> advance}. */
    private static final Map<Integer, Integer> WIDTHS = load();

    /** The pixel advance of the glyph at {@code codePoint}, accounting for bold. */
    public static int widthOf(int codePoint, boolean bold) {
        int base = WIDTHS.getOrDefault(codePoint, DEFAULT_WIDTH);
        return bold ? base + BOLD_EXTRA : base;
    }

    /**
     * The pixel advance of {@code c}. Fine for text known to be in the basic plane; a surrogate half is not
     * a glyph and is answered with the default, so use {@link #widthOf(CharSequence, boolean)} for anything
     * a player may have typed.
     */
    public static int widthOf(char c, boolean bold) {
        return widthOf((int) c, bold);
    }

    /** The pixel width {@code text} draws at, walked by code point so a surrogate pair counts once. */
    public static int widthOf(CharSequence text, boolean bold) {
        Objects.requireNonNull(text, "text");
        int total = 0;
        int index = 0;
        while (index < text.length()) {
            int codePoint = Character.codePointAt(text, index);
            total += widthOf(codePoint, bold);
            index += Character.charCount(codePoint);
        }
        return total;
    }

    /**
     * The measured table, or the handful of narrow ASCII glyphs when the resource is not on the classpath:
     * a consumer whose shade configuration drops resources keeps working, with the widths the library
     * answered before the table was measured.
     */
    private static Map<Integer, Integer> load() {
        Map<Integer, Integer> widths = fallback();
        InputStream stream = GlyphWidthTable.class.getClassLoader().getResourceAsStream("uxmlib/glyph-widths.txt");
        if (stream == null) {
            return Map.copyOf(widths);
        }
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                read(line, widths);
            }
        } catch (IOException | NumberFormatException broken) {
            // A table that will not parse is a packaging accident, not a reason to refuse to draw text.
            return Map.copyOf(fallback());
        }
        return Map.copyOf(widths);
    }

    /** One {@code codepoint advance} line of the table; blanks and {@code #} comments are skipped. */
    private static void read(String line, Map<Integer, Integer> widths) {
        String trimmed = line.trim();
        if (trimmed.isEmpty() || trimmed.charAt(0) == '#') {
            return;
        }
        int gap = trimmed.indexOf(' ');
        if (gap <= 0) {
            return;
        }
        widths.put(Integer.parseInt(trimmed.substring(0, gap), 16), Integer.parseInt(trimmed.substring(gap + 1)));
    }

    /** The narrow ASCII glyphs, which is all the library knew before the font was measured. */
    private static Map<Integer, Integer> fallback() {
        Map<Integer, Integer> widths = new HashMap<>();
        for (char narrow : new char[] {'i', '!', '.', ',', ':', ';', '\'', '|'}) {
            widths.put((int) narrow, 2);
        }
        widths.put((int) 'l', 3);
        for (char four : new char[] {' ', 'I', 't', '[', ']', '(', ')', '{', '}'}) {
            widths.put((int) four, SPACE_WIDTH);
        }
        for (char five : new char[] {'f', 'k', '<', '>'}) {
            widths.put((int) five, 5);
        }
        return widths;
    }
}
